- name: snmp ro/rw string configuration
  hosts: cisco
  gather_facts: no

  tasks:

    - name: ensure that the desired snmp strings are present
      cisco.ios.config:
        commands:
          - "snmp-server community {{ReadOnlySNMPString}} RO"
          - "snmp-server community {{ReadWriteSNMPString}} RW"
